app_netflix/project_netflix/core/urls.py
from django.urls import path

from .views import index, buscar, detalles, crear, eliminar,editar

app_name = "core"

urlpatterns = [
    path('', index, name="inicio"),
    path('buscar/', buscar, name="search"),
    path('detalles/<int:id_pelicula>', detalles, name="detail"),
    path('crear/', crear, name="create"),
    path('eliminar/<int:id_pelicula>', eliminar, name="delete"),
    path('editar/<int:id_pelicula>', editar, name="update"),
]

app_netflix/project_netflix/project_netflix/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_netflix/project_netflix/core/models.py
from django.db import models



class genero (models.Model):
    codgenero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80)

    def __str__(self):
        return self.nombre


class peliculas(models.Model):
    reseña = models.CharField(max_length=50)
    puntuacion = models.CharField(max_length=20)
    director = models.CharField(max_length=40)
    descripcion = models.TextField(blank=True)
    contenido = models.CharField(max_length=40,blank=True)
    imagen= models.ImageField(upload_to="tapas",blank=True)
    estado = models.BooleanField(default=True)
    sipnosis = models.TextField(blank=True)
    genero = models.ForeignKey(genero, on_delete=models.CASCADE)

    def __str__(self):
        return self.reseña 


    

app_netflix/project_netflix/core/views.py
from django.shortcuts import render
from .models import peliculas, genero
from django.db.models import Q

from django.http import HttpResponseRedirect
from django.urls import reverse


# vista basada en funcion que me permite renderizar
# a mi template(html)
def index(request):
    template_name = "index.html"
    # select * from peliculas
    pls = peliculas.objects.all()
    context = {
        "peliculas": pls
    }
    return render(request, template_name, context)


def buscar(request):
    template_name = "index.html"
    if request.method == "GET":
        # Guardando en una variable el valos del input
        query = request.GET.get('q')
        # filtrando de la tabla peliculas de acuerdo a la variable
        results = peliculas.objects.filter(Q(reseña__icontains=query) | Q(director__icontains=query))
        # creando un contexto con el resultado del filtro
        context = {
            "peliculas": results
        }
        # renderizando en el template
    return render(request, template_name, context)


def detalles(request, id_pelicula=None):
    template_name = "detalles.html"
    # select * from peliculas where id=?
    pel = peliculas.objects.get(pk=id_pelicula)
    context = {
        "pelicula": pel
    }
    return render(request, template_name, context)


def crear(request):
    template_name = "create.html"
    if request.method == "POST":
        vargenero = request.POST['genero']
        # todo creando el Objeto para el FK
        obj_genero = genero.objects.get(codgenero=vargenero)
        pelicula = peliculas(reseña=request.POST['reseña'],
                             descripcion=request.POST["descripcion"],
                             sipnosis=request.POST["sipnosis"],
                             director=request.POST["director"],
                             puntuacion=request.POST["puntuacion"],
                             # dato del FK pasarle todo el objeto
                             genero=obj_genero
                             )
        pelicula.save()
        return HttpResponseRedirect(reverse('core:inicio'))
    generos = genero.objects.all()
    context = {
        "generos": generos
    }
    return render(request, template_name, context)


def eliminar(request, id_pelicula=None):
    peliculas.objects.get(pk=id_pelicula).delete()
    return HttpResponseRedirect(reverse('core:inicio'))


def editar(request,id_pelicula):
    template_name = "edit.html"
    pelicula = peliculas.objects.get(pk=id_pelicula)

    if request.method == "POST":
        #vargenero = request.POST['genero']
        obj_genero = genero.objects.get(codgenero=1)
        # todo creando el Objeto para el FK
        pelicula.reseña=request.POST['reseña']
        pelicula.descripcion=request.POST['descripcion']
        pelicula.sipnosis=request.POST['sipnosis']
        pelicula.director=request.POST['director']
        pelicula.puntuacion=request.POST['puntuacion']
        pelicula.genero=obj_genero
        pelicula.save()
        return HttpResponseRedirect(reverse('core:inicio'))

    generos = genero.objects.all()
    context = {
        "pelicula":pelicula,
         "generos": generos
        }
    return render(request, template_name, context)

app_netflix/project_netflix/core/templates/base/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <nav class="navbar  navbar-dark  bg-dark navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Mi Butaca</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:inicio' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:create' %}">Peliculas</a>
              </li>
            
              
            </ul>
          </div>
        </div>
      </nav>


 {% block content %}
 {% endblock %}




    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

app_netflix/project_netflix/core/templates/create.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    <h1>Crear Una Nueva Pelicula</h1>
    <form id="create_form" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="reseña">Reseña</label>
            <input type="text" name="reseña" class="form-control" required/>
        </div>

        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <textarea name="descripcion" rows="5" class="form-control" ></textarea>
        </div>

        <div class="form-group">
            <label for="sipnosis">Sipnosis</label>
            <textarea name="sipnosis" rows="5" class="form-control"  required></textarea>
        </div>

        <div class="form-group">
            <label for="director">Director</label>
            <input type="text" name="director" class="form-control" required/>
        </div>

        <div class="form-group">
            <label for="puntuacion">Puntuacion</label>
            <input type="text" name="puntuacion" class="form-control" required />
            <small class="form-text text-muted">Desde 1 to 5 Estrellas</small>
        </div>

        <div class="form-group">
            <label for="genero">Genero</label>
            <select class="form-control form-control-lg"  name="genero"  >
                <option value="">--Seleccione--</option>
                {% for item in generos %}
                    <option value={{item.codgenero}}>{{item.nombre}}</option>
                   
                {% endfor %}
            </select>
            
        </div>
        
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-secondary" href="">Regresar</a>
            </div>
            <div class="col-md-6" style="text-align: right;">
                <button type="submit" class="btn btn-primary">Grabar</button>
            </div>
        <div>
        </div>
        </div>





    </form>
</div>


{% endblock %}

app_netflix/project_netflix/core/templates/detalles.html
{% extends 'base/base.html' %}
{% block content %}

<div class="row row-cols-1 row-cols-md-2 g-4 d-flex justify-content-center">
    <div class="col">
       <div class="m-4">
          <div class="card" style="max-width: 500px;">
        <div class="row g-0">

            {% if pelicula.imagen %}
  
            <div class="col-sm-5" style="background: #868e96;">
                <img src={{pelicula.imagen.url}} class="card-img-top h-100" alt="...">
            </div>
            {% else %}
            <div class="col-sm-5" style="background: #868e96;">
                <img src="" class="card-img-top h-100" alt="Sin Imagen por Ahora">
            </div>

            {% endif %}
  
        <div class="col-sm-7">
            <div class="card-body">
                <h5 class="card-title">{{pelicula.reseña}}</h5>
                <h5 class="card-title">{{pelicula.puntuacion}}</h5>
                <p class="card-text" style="text-align:justify">{{pelicula.descripcion}}</p>
                <h5 class="card-title">{{pelicula.genero}}</h5>
            </div>
  
            <div class="container">
                <div class="row">
                <div class="card-body">
                 <a href="{% url 'core:inicio' %}" class="btn btn-success ">Volver</a>
                 
                </div>
            </div>
           </div>
        </div>
    </div>
    </div>
  </div>
  </div>
  </div>


{% endblock %}

app_netflix/project_netflix/core/templates/edit.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    <h1>Crear Una Nueva Pelicula</h1>
    <form id="create_form" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="reseña">Reseña</label>
            <input type="text" name="reseña" class="form-control" value ="{{pelicula.reseña}}" required/>
        </div>

        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <textarea name="descripcion" rows="5" class="form-control">{{pelicula.descripcion}}</textarea>
        </div>

        <div class="form-group">
            <label for="sipnosis">Sipnosis</label>
            <textarea name="sipnosis" rows="5" class="form-control" > {{pelicula.sipnosis}}"</textarea>
        </div>

        <div class="form-group">
            <label for="director">Director</label>
            <input type="text" name="director" class="form-control" value ="{{pelicula.director}}" required/>
        </div>

        <div class="form-group">
            <label for="puntuacion">Puntuacion</label>
            <input type="text" name="puntuacion" class="form-control" value ="{{pelicula.puntuacion}}" required />
            <small class="form-text text-muted">Desde 1 to 5 Estrellas</small>
        </div>

        <div class="form-group">
            <label for="genero">Genero</label>
            <select class="form-control form-control-lg"  name="genero"  >
                <option value="">--Seleccione--</option>
                {% for item in generos %}
                    <option value={{item.codgenero}}>{{item.nombre}}</option>
                   
                {% endfor %}
            </select>
            
        </div>
        
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-secondary" href="">Regresar</a>
            </div>
            <div class="col-md-6" style="text-align: right;">
                <button type="submit" class="btn btn-primary">Grabar</button>
            </div>
        <div>
        </div>
        </div>

    </form>
</div>


{% endblock %}

app_netflix/project_netflix/core/templates/index.html
{% extends 'base/base.html' %}

{% block content %}

<h1 style="text-align: center;">Clasicos en NetFlix - Reseña de Movies</h1>

<div class="m-4">

 <div class="container">
    <div class="row  height d-flex justify-content-center align-items-center">
      <div class="col-md-5">
        <form method="GET" action="{% url 'core:search' %}">
          <i class="fa fa-search"></i>
          <input type="text" name="q" class="form-control form-input" placeholder="Ingrese la Palabra Clave" >
          <span class="left-pan"><i class="fa fa-microphone"></i></span>
      </div>
      </form>
    </div>

 </div> 

<div class="row row-cols-1 row-cols-md-2 g-4">
  {% for item in peliculas %}
  <div class="col">
     <div class="m-4">
        <div class="card" style="max-width: 500px;">
      <div class="row g-0">

        {% if item.imagen %}

          <div class="col-sm-5" style="background: #868e96;">
            <a href="{% url 'core:detail' item.id %}" >
              <img src={{item.imagen.url}} class="card-img-top h-100" alt="...">
            </a> 
          </div>
        {% else %}
        <div class="col-sm-5" style="background: #868e96;">
          <a href="{% url 'core:detail' item.id %}" >
            <img src="" class="card-img-top h-100" alt="Sin Imagen por Ahora">
          </a> 
        </div>
        {% endif %}

      <div class="col-sm-7">
          <div class="card-body">
              <h5 class="card-title">{{item.reseña}}</h5>
              <p>{{item.director}}</p>
              <p class="card-text" style="text-align:justify">{{item.descripcion}}</p>
          </div>

          <div class="container">
              <div class="row">
              <div class="card-body">
               <a href="{% url 'core:update' item.id  %}" class="btn btn-success ">Actualizar</a>
               <a href="{% url 'core:delete' item.id %}" class="btn btn-danger">Eliminar</a>
              </div>
          </div>
         </div>
      </div>
  </div>
  </div>
</div>
</div>
{% endfor %}
</div>



{% endblock %}